"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "RankChecker"
DATA_FILES = ['icon/ranking-icon.png']

OPTIONS = {'argv_emulation': True,
           'iconfile': 'icon/Jamespeng-Movie-Ranking.icns',
           'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Making RankChecker",
            'CFBundleIdentifier': "",
            'CFBundleVersion': "0.1.0",
            'CFBundleShortVersionString': "0.1.0",
            'NSHumanReadableCopyright': "Copyright © 2020, Nokkun, All Rights Reserved",
            'PyRuntimeLocations': [
                '@executable_path/../Frameworks/libpython3.7m.dylib',
                '/opt/anaconda3/lib/libpython3.7m.dylib'
               ]
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
